// Action types
export const FETCH_SURAH_REQUEST = 'FETCH_SURAH_REQUEST';
export const FETCH_SURAH_SUCCESS = 'FETCH_SURAH_SUCCESS';
export const FETCH_SURAH_FAILURE = 'FETCH_SURAH_FAILURE';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';
export const NO_REPOS = 'NO_REPOS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const ADD_COURSE= 'ADD_COURSE';
export const DELETE_COURSE= 'DELETE_COURSE';
export const GET_COURSE ='GET_COURSE';
export const GET_INSTRUCTOR_COURSES ='GET_INSTRUCTOR_COURSES';
export const GET_COURSES ='GET_COURSES';
export const COURSE_ERROR ='COURSE_ERROR';
export const ENROLL_COURSE_SUCCESS= 'ENROLL_COURSE_SUCCESS';
export const GET_ENROLLMENTS_SUCCESS='GET_ENROLLMENTS_SUCCESS';
export const GET_ENROLLMENTS_FAIL='GET_ENROLLMENTS_FAIL';
export const ENROLL_COURSE_FAIL = 'ENROLL_COURSE_FAIL';
export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS';
export const ANNOUNCEMENTS_ERROR = 'ANNOUNCEMENTS_ERROR';
export const RESET_ANNOUNCEMENTS = 'RESET_ANNOUNCEMENTS';
export const ADD_ANNOUNCEMENTS = 'ADD_ANNOUNCEMENTS';
export const  ASSIGNMENT_UPLOAD_SUCCESS = ' ASSIGNMENT_UPLOAD_SUCCESS';
export const  ASSIGNMENT_UPLOAD_FAIL = ' ASSIGNMENT_UPLOAD_FAIL';
export const  RESET_ASSIGNMENTS = ' RESET_ASSIGNMENTS';
export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS';
export const CLEAR_UPLOAD_FORM = 'CLEAR_UPLOAD_FORM';
export const GET_ASSIGNMENTS_SUCCESS ='GET_ASSIGNMENTS_SUCCESS';
export const GET_ASSIGNMENTS_FAIL ='GET_ASSIGNMENTS_FAIL';
export const GET_ASSIGNMENT_SUCCESS ='GET_ASSIGNMENT_SUCCESS';
export const GET_ASSIGNMENT_FAIL ='GET_ASSIGNMENT_FAIL';
export const DOWNLOAD_ASSIGNMENT_SUCCESS ='DOWNLOAD_ASSIGNMENT_SUCCESS';
export const DOWNLOAD_ASSIGNMENT_FAIL ='DOWNLOAD_ASSIGNMENT_FAIL';
export const UPLOAD_SOLUTION_REQUEST = 'UPLOAD_SOLUTION_REQUEST';
export const UPLOAD_SOLUTION_SUCCESS = 'UPLOAD_SOLUTION_SUCCESS';
export const UPLOAD_SOLUTION_FAILURE = 'UPLOAD_SOLUTION_FAILURE';

export const UPLOADED_SOLUTION_REQUEST = 'UPLOADED_SOLUTION_REQUEST';
export const UPLOADED_SOLUTION_SUCCESS = 'UPLOADED_SOLUTION_SUCCESS';
export const UPLOADED_SOLUTION_FAILURE = 'UPLOADED_SOLUTION_FAILURE';

export const FETCH_QUIZ_REQUEST = 'FETCH_QUIZ_REQUEST';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_FAILURE = 'FETCH_QUIZ_FAILURE';



export const FETCH_ATTEMPT_QUIZ_REQUEST = 'FETCH_ATTEMPT_QUIZ_REQUEST';
export const FETCH_ATTEMPT_QUIZ_SUCCESS = 'FETCH_ATTEMPT_QUIZ_SUCCESS';
export const FETCH_ATTEMPT_QUIZ_FAILURE = 'FETCH_ATTEMPT_QUIZ_FAILURE';

// actions/types.js
export const FETCH_QUIZZES_REQUEST = 'FETCH_QUIZZES_REQUEST';
export const FETCH_QUIZZES_SUCCESS = 'FETCH_QUIZZES_SUCCESS';
export const FETCH_QUIZZES_FAILURE = 'FETCH_QUIZZES_FAILURE';

export const POST_QUIZ = 'POST_QUIZ';
export const POST_QUIZ_SUCCESS = 'POST_QUIZ_SUCCESS';
export const POST_QUIZ_FAILURE = 'POST_QUIZ_FAILURE';

export const ATTEMPT_QUIZ = 'ATTEMP_QUIZ'
export const ATTEMPT_QUIZ_SUCCESS= 'ATTEMP_QUIZ_SUCCESS'
export const ATTEMPT_QUIZ_FAILURE= 'ATTEMP_QUIZ_FAILURE'

export const FETCH_COURSE_CONTENT_REQUEST = 'FETCH_COURSE_CONTENT_REQUEST';
export const FETCH_COURSE_CONTENT_SUCCESS = 'FETCH_COURSE_CONTENT_SUCCESS';
export const FETCH_COURSE_CONTENT_FAILURE = 'FETCH_COURSE_CONTENT_FAILURE';

export const FETCH_COURSE_CONTENTS_REQUEST = 'FETCH_COURSE_CONTENTS_REQUEST';
export const FETCH_COURSE_CONTENTS_SUCCESS = 'FETCH_COURSE_CONTENTS_SUCCESS';
export const FETCH_COURSE_CONTENTS_FAILURE = 'FETCH_COURSE_CONTENTS_FAILURE';

export const COURSE_CONTENT_UPLOAD_SUCCESS = 'COURSE_CONTENT_UPLOAD_SUCCESS';
export const COURSE_CONTENT_UPLOAD_FAIL = 'COURSE_CONTENT_UPLOAD_FAIL';

export const DOWNLOAD_COURSE_CONTENT_SUCCESS = 'DOWNLOAD_COURSE_CONTENT_SUCCESS';
export const DOWNLOAD_COURSE_CONTENT_FAIL = 'DOWNLOAD_COURSE_CONTENT_FAIL'




